### ISSUE TITLE
Problem when deploying the model with Tensorflow serving

### ISSUE THREAD

**Issue by Ekkalak-T** [sertiscorp/thai-word-segmentation#2]
I have completed deploying saved model in Tensorflow serving on a server side but I have a problem when client trying to match the input tensor format with the saved model.

**save_model function in model.py**

```
inputs = {
'inputs': tf.saved_model.utils.build_tensor_info(tf.identity(self.tf_tokens_batch, 'inputs')),
'lengths': tf.saved_model.utils.build_tensor_info(tf.identity(self.tf_lengths_batch, 'lengths')),
'training': tf.saved_model.utils.build_tensor_info(tf.identity(self.tf_training, 'training'))
}

outputs = {
'outputs': tf.saved_model.utils.build_tensor_info(tf.identity(self.tf_masked_prediction, 'outputs'))
}
```

**client.py (my implementation)**
```
text = "ทดสอบ"
inputs = [ThaiWordSegmentLabeller.get_input_labels(text)]
lengths = [len(text)]
request.model_spec.name = 'word'
request.model_spec.signature_name = 'word_segmentation'

request.inputs['inputs'].CopyFrom(tf.contrib.util.make_tensor_proto(values=inputs,dtype=tf.int64))
request.inputs['lengths'].CopyFrom(tf.contrib.util.make_tensor_proto(values=lengths,dtype=tf.int64))
request.inputs['training'].CopyFrom(tf.contrib.util.make_tensor_proto(values=False,dtype=tf.bool))
```

**Output**
```
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="You must feed a value for placeholder tensor 'Placeholder_1' with dtype bool
         [[Node: Placeholder_1 = Placeholder[_output_shapes=[[]], dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]")
```

Best Regards,

**Comment by statguy** [comment]
I didn't give specific names for the input variables in the prediction graph so the names are default what TF gives and are different from what the `save_model` function specifies. Please look at `predict_example.py` how to obtain the input variables.

**Comment by Ekkalak-T** [comment]
@statguy Thank you so much for replying. 

Did you mean these input variables?

`g_inputs = 'IteratorGetNext:1'
g_lengths = 'IteratorGetNext:0'
g_training = 'Placeholder_1:0'
g_outputs = 'boolean_mask_1/Gather:0'`

Unfortunately, I have tried these variables but also got an error related to tensor alias. 
`grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="input tensor alias not found in signature: IteratorGetNext:0. Inputs expected to be in the set {lengths, inputs, training}.")`

**client.py**
```
text = "ทดสอบ"
inputs = [ThaiWordSegmentLabeller.get_input_labels(text)]
lengths = [len(text)]
request.model_spec.name = 'word'
request.model_spec.signature_name = 'word_segmentation'

g_inputs = 'IteratorGetNext:1'
g_lengths = 'IteratorGetNext:0'
g_training = 'Placeholder_1:0'
g_outputs = 'boolean_mask_1/Gather:0'

request.inputs[g_inputs].CopyFrom(
tf.contrib.util.make_tensor_proto(inputs,shape=[inputs.shape[0]],dtype=tf.int64))
request.inputs[g_lengths].CopyFrom(
tf.contrib.util.make_tensor_proto(lengths,dtype=tf.int64))
request.inputs[g_training].CopyFrom(
tf.contrib.util.make_tensor_proto(False,dtype=tf.bool))

```

**Comment by statguy** [comment]
I updated predict_example.py to use the signature names. Does it help?

**Comment by Ekkalak-T** [comment]
@statguy Thank you so much for fixing the issue and I would like to thank again for contributing such an amazing application. 

This model works perfectly with my training data. I am going to write an article about how I apply it in my domain and I will refer to your article and Github.
