### ISSUE TITLE
Duplicate writing training data in preprocessing.py?

### ISSUE THREAD

**Issue by Ekkalak-T** [sertiscorp/thai-word-segmentation#3]
https://github.com/sertiscorp/thai-word-segmentation/blob/5c77e020d592eef38c20a89a81e1c3eb957ecac8/preprocess.py#L44-L51

At line number 47, it looks like the data is not splitted correctly. I am not sure whether this line should be removed as we should write the data only once based on random variable p.

**Comment by statguy** [comment]
You are right, so I removed the line and retrained the model with a new split. Thanks for spotting this!
