### ISSUE TITLE
Lao word segmentation Issue

### ISSUE THREAD

**Issue by huelee2020** [sertiscorp/thai-word-segmentation#4]
I saw your report with such high accuracy, I am Lao student studying master in computer science in China now, I saw your project is very interesting and I also have an idea to do so for Lao word segmentation and pos tagging, what does the Lao corpus look like which i should prepare and I want to try to code such thing for Lao language.

Please give me any idea

**Comment by statguy** [comment]
Thanks for finding interest in the word segmenter. To adapt the current approach to the Lao language, you would need these three steps:

- Change the character embeddings to support Lao Unicode block. This is a minor and easy fix.
- Prepare a Lao corpus. This would require gathering text documents in Lao language and separating words in the documents by hand. The format of the file is just a text file where the words are separated by the pipe character '|', e.g. `กฎหมาย|กับ|การ|เบียดบัง|คน|จน|`, and it is a good idea to separate each sentence to its own line. The more documents in diverse fields there are, the better the word segmenter accuracy will be.
- Train the model with the Lao corpus.

Feel free to contact me directly via email [jvj@iki.fi](mailto:jvj@iki.fi) for more help.

**Comment by huelee2020** [comment]
Firstly I would like to say thank you very much for your time
I will follow as you suggested and then found any problem which I don't
understand I will contact you directly email. And if I have any progress I
will let you know too

Thank you again  thank you very much
