### ISSUE TITLE
Sentence segmentation

### ISSUE THREAD

**Issue by Querela** [sertiscorp/thai-word-segmentation#6]
Hi,
I was looking for a tool to do thai sentence segmentation. But there seems to be no readily available tool. Paper propose methods for use cases like thai-engl translation [1] or disambiguation of space characters as sentence markers [2] according to the number of verbs (morphemes) / rule-based / discourse analysis.

Do you know a tool for this task or is it possible to use your word segmentation tool as part of a toolchain to do sentence segmentation?

Thank you in advance for any reply. Best regards.

PS.: using your tool to apply space characters between each "word" seems to improve the result of google translate (for single sentences). :-) Well, my sample size was not that large ...

[1] http://www.aclweb.org/anthology/W10-3602  
[2] http://pioneer.netserv.chula.ac.th/~awirote/ling/snlp2007-wirote.pdf

**Comment by statguy** [comment]
We are not aware of any publicly available tools for Thai sentence segmentation apart from some toy examples. If we assume, for example, that a sentence must have a finite verb to be qualified as a sentence, we could add POS tagging to the word segmentation approach to recognize verbs and then possibly jointly do sentence segmentation. In addition of modifications to the model, this obviously requires training data as well.
